### ISSUE TITLE
Memory free() error

### ISSUE THREAD

**Issue by naokiuchida** [lips-hci/openni2_linux#3]
Hi, 

I'm having a problem while trying to test Ni2SimpleViewer in my environment: Ubuntu 16.04, 4.15.0-39-generic with LIPS DL. 

I could build source files and execute the program but after I chose some random number at the initial dialogue, it crashed with a message something like the following: 

mydir@ubuntu:Ni2SimpleViewer$ ./Ni2SimpleViewer 
1) Depth only
2) Image only
3) IR only
4) Depth and Image
5) Depth and IR
6) Image and IR
7) All
0) Exit
Please input your choice : 7
Initialilzation OK
INFO	Detecting depth camera...
INFO	Depth camera VID:PID = 2DF2:0213
INFO	Detecting rgb camera...
INFO	RGB camera VID:PID = 2DF2:0215
INFO	No local config found. Using default config.
Invalid device node
open rts video device fail
ERROR	Cannot find RGB device or unsupported!(No such file or directory)
ERROR	errno: Failed to probe TOF device! (2:No such file or directory)

Press any key to EXIT the program...
*** Error in `./Ni2SimpleViewer': free(): invalid pointer: 0x00007f489a9a9d80 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f48bc6777e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f48bc68037a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f48bc68453c]
/usr/lib/libdevicesensor.so(_ZN11lips_configD2Ev+0x1c)[0x7f489a6424ec]
/lib/x86_64-linux-gnu/libc.so.6(+0x39ff8)[0x7f48bc639ff8]
/lib/x86_64-linux-gnu/libc.so.6(+0x3a045)[0x7f48bc63a045]
/usr/lib/libdevicesensor.so(+0x16cc4e)[0x7f489a72fc4e]
/usr/lib/libdevicesensor.so(_ZN10LIPSLogger3logE8LogLevelPKc+0x69)[0x7f489a72f6b9]
/usr/lib/libdevicesensor.so(_ZN17LIPSLoggerWrapper3LogE8LogLevelPKcz+0x216)[0x7f489a72f436]
/usr/lib/libdevicesensor.so(_Z16tof_sensor_probeP13sensor_device+0x68)[0x7f489a6de9a8]
/usr/lib/libdevicesensor.so(_Z16lips_module_initPFbPvE+0x35d)[0x7f489a6e079d]
/usr/lib/libdevicesensor.so(_ZN10LIPSDevice10initCameraEv+0x5a1)[0x7f489a603741]
/usr/lib/libdevicesensor.so(+0x168c05)[0x7f489a72bc05]
/usr/lib/libdevicesensor.so(_Z17getSupportedModes10CameraTypeRSt6vectorI10ResolutionSaIS1_EERS0_IjSaIjEE+0x11)[0x7f489a72d631]
/home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libmodule-lips2.so(+0x13e57)[0x7f489cf3ce57]
/home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libmodule-lips2.so(+0x12732)[0x7f489cf3b732]
./libOpenNI2.so(+0xcbf2)[0x7f48bff42bf2]
./Ni2SimpleViewer[0x403139]
./Ni2SimpleViewer[0x401ad4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f48bc620830]
./Ni2SimpleViewer[0x4017c9]
======= Memory map: ========
00400000-00405000 r-xp 00000000 07:00 2493900                            /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/Ni2SimpleViewer
00605000-00606000 rw-p 00005000 07:00 2493900                            /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/Ni2SimpleViewer
016be000-025be000 rw-p 00000000 00:00 0                                  [heap]
200000000-200200000 rw-s 00000000 00:06 494                              /dev/nvidiactl
200200000-200400000 ---p 00000000 00:00 0 
200400000-200404000 rw-s 00000000 00:06 494                              /dev/nvidiactl
200404000-200600000 ---p 00000000 00:00 0 
200600000-200a00000 rw-s 00000000 00:06 494                              /dev/nvidiactl
200a00000-201600000 ---p 00000000 00:00 0 
201600000-201800000 rw-s 00000000 00:06 494                              /dev/nvidiactl
201800000-201804000 rw-s 00000000 00:06 494                              /dev/nvidiactl
201804000-201a00000 ---p 00000000 00:00 0 
201a00000-201e00000 rw-s 00000000 00:06 494                              /dev/nvidiactl
201e00000-201e04000 rw-s 00000000 00:06 494                              /dev/nvidiactl
201e04000-202000000 ---p 00000000 00:00 0 
202000000-202400000 rw-s 00000000 00:06 494                              /dev/nvidiactl
202400000-202404000 rw-s 00000000 00:06 494                              /dev/nvidiactl
202404000-202600000 ---p 00000000 00:00 0 
202600000-202a00000 rw-s 00000000 00:06 494                              /dev/nvidiactl
202a00000-202a04000 rw-s 00000000 00:06 494                              /dev/nvidiactl
202a04000-202c00000 ---p 00000000 00:00 0 
202c00000-203000000 rw-s 00000000 00:06 494                              /dev/nvidiactl
203000000-203004000 rw-s 00000000 00:06 494                              /dev/nvidiactl
203004000-203200000 ---p 00000000 00:00 0 
203200000-203600000 rw-s 00000000 00:06 494                              /dev/nvidiactl
203600000-203604000 rw-s 00000000 00:06 494                              /dev/nvidiactl
203604000-203800000 ---p 00000000 00:00 0 
203800000-203c00000 rw-s 00000000 00:06 494                              /dev/nvidiactl
203c00000-203c04000 rw-s 00000000 00:06 494                              /dev/nvidiactl
203c04000-203e00000 ---p 00000000 00:00 0 
203e00000-204200000 rw-s 00000000 00:06 494                              /dev/nvidiactl
204200000-204204000 rw-s 00000000 00:06 494                              /dev/nvidiactl
204204000-204400000 ---p 00000000 00:00 0 
204400000-204800000 rw-s 00000000 00:06 494                              /dev/nvidiactl
204800000-204804000 rw-s 00000000 00:06 494                              /dev/nvidiactl
204804000-204a00000 ---p 00000000 00:00 0 
204a00000-204e00000 rw-s 00000000 00:06 494                              /dev/nvidiactl
204e00000-204e04000 rw-s 00000000 00:06 494                              /dev/nvidiactl
204e04000-205000000 ---p 00000000 00:00 0 
205000000-205400000 rw-s 00000000 00:06 494                              /dev/nvidiactl
205400000-205404000 rw-s 00000000 00:06 494                              /dev/nvidiactl
205404000-205600000 ---p 00000000 00:00 0 
205600000-205a00000 rw-s 00000000 00:06 494                              /dev/nvidiactl
205a00000-205a04000 rw-s 00000000 00:06 494                              /dev/nvidiactl
205a04000-205c00000 ---p 00000000 00:00 0 
205c00000-206000000 rw-s 00000000 00:06 494                              /dev/nvidiactl
206000000-206004000 rw-s 00000000 00:06 494                              /dev/nvidiactl
206004000-206200000 ---p 00000000 00:00 0 
206200000-206600000 rw-s 00000000 00:06 494                              /dev/nvidiactl
206600000-206604000 rw-s 00000000 00:06 494                              /dev/nvidiactl
206604000-206800000 ---p 00000000 00:00 0 
206800000-206c00000 rw-s 00000000 00:06 494                              /dev/nvidiactl
206c00000-206c04000 rw-s 00000000 00:06 494                              /dev/nvidiactl
206c04000-206e00000 ---p 00000000 00:00 0 
206e00000-207200000 rw-s 00000000 00:06 494                              /dev/nvidiactl
207200000-207400000 ---p 00000000 00:00 0 
207400000-207600000 rw-s 00000000 00:06 494                              /dev/nvidiactl
207600000-300200000 ---p 00000000 00:00 0 
10000000000-10200200000 ---p 00000000 00:00 0 
7f4850000000-7f4858000000 ---p 00000000 00:00 0 
7f4858000000-7f4858021000 rw-p 00000000 00:00 0 
7f4858021000-7f485c000000 ---p 00000000 00:00 0 
7f485c000000-7f485c021000 rw-p 00000000 00:00 0 
7f485c021000-7f4860000000 ---p 00000000 00:00 0 
7f4860000000-7f4860001000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860001000-7f4860002000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860002000-7f4860003000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860003000-7f4860004000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860004000-7f4860005000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860005000-7f4860006000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860006000-7f4860007000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860007000-7f4860008000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860008000-7f4860009000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860009000-7f486000a000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f486000a000-7f486000b000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f486000b000-7f486000c000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f486000c000-7f486000d000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f486000d000-7f486000e000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f486000e000-7f486000f000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f486000f000-7f4860010000 rw-s 00000000 00:06 495                        /dev/nvidia0
7f4860010000-7f4870000000 ---p 00000000 00:00 0 
7f4871ffc000-7f4871ffd000 ---p 00000000 00:00 0 
7f4871ffd000-7f48727fd000 rwxp 00000000 00:00 0 
7f48727fd000-7f48727fe000 ---p 00000000 00:00 0 
7f48727fe000-7f4872ffe000 rwxp 00000000 00:00 0 
7f4872ffe000-7f4872fff000 ---p 00000000 00:00 0 
7f4872fff000-7f48737ff000 rwxp 00000000 00:00 0 
7f48737ff000-7f4873800000 ---p 00000000 00:00 0 
7f4873800000-7f4874000000 rwxp 00000000 00:00 0 
7f4874000000-7f4876400000 ---p 00000000 00:00 0 
7f4876400000-7f4876600000 rw-s 00000000 00:05 43052                      /dev/zero (deleted)
7f4876600000-7f4876800000 rw-s 00000000 00:06 494                        /dev/nvidiactl
7f4876800000-7f4876a00000 rw-s 00000000 00:05 43053                      /dev/zero (deleted)
7f4876a00000-7f4876c00000 rw-s 00000000 00:06 494                        /dev/nvidiactl
7f4876c00000-7f4876e00000 ---p 00000000 00:00 0 
7f4876e00000-7f48770d6000 rw-s 00000000 00:06 494                        /dev/nvidiactl
7f48770d6000-7f4878000000 ---p 00000000 00:00 0 
7f4878000000-7f4878021000 rw-p 00000000 00:00 0 
7f4878021000-7f487c000000 ---p 00000000 00:00 0 
7f487c51a000-7f487c51b000 ---p 00000000 00:00 0 
7f487c51b000-7f487cd1b000 rwxp 00000000 00:00 0 
7f487cd1b000-7f487d2c1000 rw-p 00000000 00:00 0 
7f487d2c1000-7f487d2c2000 ---p 00000000 00:00 0 
7f487d2c2000-7f487dac2000 rwxp 00000000 00:00 0 
7f487dac2000-7f487e844000 r-xp 00000000 07:00 155011                     /usr/lib/x86_64-linux-gnu/libcuda.so.410.72
7f487e844000-7f487ea44000 ---p 00d82000 07:00 155011                     /usr/lib/x86_64-linux-gnu/libcuda.so.410.72
7f487ea44000-7f487ebb2000 rw-p 00d82000 07:00 155011                     /usr/lib/x86_64-linux-gnu/libcuda.so.410.72
7f487ebb2000-7f487ebc2000 rw-p 00000000 00:00 0 
7f487ebde000-7f487ec07000 rw-p 00000000 00:00 0 
7f487ec07000-7f4884c07000 ---p 00000000 00:00 0 
7f4884c07000-7f4884c44000 r-xp 00000000 07:00 159336                     /usr/lib/nvidia-410/libnvidia-fatbinaryloader.so.410.72
7f4884c44000-7f4884e44000 ---p 0003d000 07:00 159336                     /usr/lib/nvidia-410/libnvidia-fatbinaryloader.so.410.72
7f4884e44000-7f4884e4f000 rw-p 0003d000 07:00 159336                     /usr/lib/nvidia-410/libnvidia-fatbinaryloader.so.410.72
7f4884e4f000-7f4884e54000 rw-p 00000000 00:00 0 
7f4884e54000-7f4886805000 r-xp 00000000 07:00 155014                     /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.410.72
7f4886805000-7f4886a04000 ---p 019b1000 07:00 155014                     /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.410.72
7f4886a04000-7f4886b77000 rw-p 019b0000 07:00 155014                     /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.410.72
7f4886b77000-7f4886b87000 rw-p 00000000 00:00 0 
7f4886b87000-7f4886b8c000 r-xp 00000000 07:00 162161                     /usr/local/cuda-9.0/targets/x86_64-linux/lib/libOpenCL.so.1.0.0
7f4886b8c000-7f4886d8b000 ---p 00005000 07:00 162161                     /usr/local/cuda-9.0/targets/x86_64-linux/lib/libOpenCL.so.1.0.0
7f4886d8b000-7f4886d8d000 rw-p 00004000 07:00 162161                     /usr/local/cuda-9.0/targets/x86_64-linux/lib/libOpenCL.so.1.0.0
7f4886d8d000-7f4886d8e000 ---p 00000000 00:00 0 
7f4886d8e000-7f488758e000 rwxp 00000000 00:00 0 
7f4887735000-7f4887975000 rw-p 00000000 00:00 0 
7f4887975000-7f488797d000 r-xp 00000000 07:00 135356                     /usr/lib/libbilateralfilter.so
7f488797d000-7f4887b7d000 ---p 00008000 07:00 135356                     /usr/lib/libbilateralfilter.so
7f4887b7d000-7f4887b7e000 r--p 00008000 07:00 135356                     /usr/lib/libbilateralfilter.so
7f4887b7e000-7f4887b7f000 rw-p 00009000 07:00 135356                     /usr/lib/libbilateralfilter.so
7f4887b7f000-7f4887f1b000 r-xp 00000000 07:00 146393                     /usr/local/lib/libopencv_cudaoptflow.so.3.1.0
7f4887f1b000-7f488811a000 ---p 0039c000 07:00 146393                     /usr/local/lib/libopencv_cudaoptflow.so.3.1.0
7f488811a000-7f488811c000 rw-p 0039b000 07:00 146393                     /usr/local/lib/libopencv_cudaoptflow.so.3.1.0
7f488811c000-7f4888131000 r-xp 00000000 07:00 143525                     /usr/local/lib/libopencv_cudacodec.so.3.1.0
7f4888131000-7f4888330000 ---p 00015000 07:00 143525                     /usr/local/lib/libopencv_cudacodec.so.3.1.0
7f4888330000-7f4888331000 rw-p 00014000 07:00 143525                     /usr/local/lib/libopencv_cudacodec.so.3.1.0
7f4888331000-7f488c79a000 r-xp 00000000 07:00 135364                     /usr/local/lib/libopencv_cudaarithm.so.3.1.0
7f488c79a000-7f488c999000 ---p 04469000 07:00 135364                     /usr/local/lib/libopencv_cudaarithm.so.3.1.0
7f488c999000-7f488c99f000 rw-p 04468000 07:00 135364                     /usr/local/lib/libopencv_cudaarithm.so.3.1.0
7f488c99f000-7f488cb41000 rw-p 00000000 00:00 0 
7f488cb41000-7f4896556000 r-xp 00000000 07:00 135593                     /usr/local/lib/libopencv_cudafilters.so.3.1.0
7f4896556000-7f4896756000 ---p 09a15000 07:00 135593                     /usr/local/lib/libopencv_cudafilters.so.3.1.0
7f4896756000-7f4896764000 rw-p 09a15000 07:00 135593                     /usr/local/lib/libopencv_cudafilters.so.3.1.0
7f4896764000-7f4896765000 rw-p 00000000 00:00 0 
7f4896765000-7f48974d2000 r-xp 00000000 07:00 135596                     /usr/local/lib/libopencv_cudaimgproc.so.3.1.0
7f48974d2000-7f48976d1000 ---p 00d6d000 07:00 135596                     /usr/local/lib/libopencv_cudaimgproc.so.3.1.0
7f48976d1000-7f48976d7000 rw-p 00d6c000 07:00 135596                     /usr/local/lib/libopencv_cudaimgproc.so.3.1.0
7f48976d7000-7f48976f2000 rw-p 00000000 00:00 0 
7f48976f2000-7f4898e5e000 r-xp 00000000 07:00 141756                     /usr/local/lib/libopencv_cudawarping.so.3.1.0
7f4898e5e000-7f489905d000 ---p 0176c000 07:00 141756                     /usr/local/lib/libopencv_cudawarping.so.3.1.0
7f489905d000-7f4899062000 rw-p 0176b000 07:00 141756                     /usr/local/lib/libopencv_cudawarping.so.3.1.0
7f4899062000-7f4899063000 rw-p 00000000 00:00 0 
7f4899063000-7f48993f0000 r-xp 00000000 07:00 146387                     /usr/local/lib/libopencv_cudalegacy.so.3.1.0
7f48993f0000-7f48995ef000 ---p 0038d000 07:00 146387                     /usr/local/lib/libopencv_cudalegacy.so.3.1.0
7f48995ef000-7f48995f2000 rw-p 0038c000 07:00 146387                     /usr/local/lib/libopencv_cudalegacy.so.3.1.0
7f48995f2000-7f48995f5000 rw-p 00000000 00:00 0 
7f48995f5000-7f489a3be000 r-xp 00000000 07:00 146384                     /usr/local/lib/libopencv_cudafeatures2d.so.3.1.0
7f489a3be000-7f489a5be000 ---p 00dc9000 07:00 146384                     /usr/local/lib/libopencv_cudafeatures2d.so.3.1.0
7f489a5be000-7f489a5c1000 rw-p 00dc9000 07:00 146384                     /usr/local/lib/libopencv_cudafeatures2d.so.3.1.0
7f489a5c1000-7f489a5c3000 rw-p 00000000 00:00 0 
7f489a5c3000-7f489a7a2000 r-xp 00000000 07:00 135353                     /usr/lib/libdevicesensor.so
7f489a7a2000-7f489a9a1000 ---p 001df000 07:00 135353                     /usr/lib/libdevicesensor.so
7f489a9a1000-7f489a9a5000 r--p 001de000 07:00 135353                     /usr/lib/libdevicesensor.so
7f489a9a5000-7f489a9aa000 rw-p 001e2000 07:00 135353                     /usr/lib/libdevicesensor.so
7f489a9aa000-7f489ad84000 rw-p 00000000 00:00 0 
7f489ad84000-7f489ad88000 r-xp 00000000 07:00 1578420                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f489ad88000-7f489af87000 ---p 00004000 07:00 1578420                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f489af87000-7f489af88000 r--p 00003000 07:00 1578420                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f489af88000-7f489af89000 rw-p 00004000 07:00 1578420                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f489af89000-7f489afdd000 r-xp 00000000 07:00 135367                     /usr/local/lib/libopencv_flann.so.3.1.0
7f489afdd000-7f489b1dd000 ---p 00054000 07:00 135367                     /usr/local/lib/libopencv_flann.so.3.1.0
7f489b1dd000-7f489b1e0000 rw-p 00054000 07:00 135367                     /usr/local/lib/libopencv_flann.so.3.1.0
7f489b1e0000-7f489b29c000 r-xp 00000000 07:00 135576                     /usr/local/lib/libopencv_ml.so.3.1.0
7f489b29c000-7f489b49b000 ---p 000bc000 07:00 135576                     /usr/local/lib/libopencv_ml.so.3.1.0
7f489b49b000-7f489b49e000 rw-p 000bb000 07:00 135576                     /usr/local/lib/libopencv_ml.so.3.1.0
7f489b49e000-7f489b626000 r-xp 00000000 07:00 141762                     /usr/local/lib/libopencv_photo.so.3.1.0
7f489b626000-7f489b826000 ---p 00188000 07:00 141762                     /usr/local/lib/libopencv_photo.so.3.1.0
7f489b826000-7f489b829000 rw-p 00188000 07:00 141762                     /usr/local/lib/libopencv_photo.so.3.1.0
7f489b829000-7f489b9ab000 r-xp 00000000 07:00 135581                     /usr/local/lib/libopencv_video.so.3.1.0
7f489b9ab000-7f489bbaa000 ---p 00182000 07:00 135581                     /usr/local/lib/libopencv_video.so.3.1.0
7f489bbaa000-7f489bbae000 rw-p 00181000 07:00 135581                     /usr/local/lib/libopencv_video.so.3.1.0
7f489bbae000-7f489bc75000 r-xp 00000000 07:00 146378                     /usr/local/lib/libopencv_features2d.so.3.1.0
7f489bc75000-7f489be75000 ---p 000c7000 07:00 146378                     /usr/local/lib/libopencv_features2d.so.3.1.0
7f489be75000-7f489be7a000 rw-p 000c7000 07:00 146378                     /usr/local/lib/libopencv_features2d.so.3.1.0
7f489be7a000-7f489bfef000 r-xp 00000000 07:00 146381                     /usr/local/lib/libopencv_calib3d.so.3.1.0
7f489bfef000-7f489c1ee000 ---p 00175000 07:00 146381                     /usr/local/lib/libopencv_calib3d.so.3.1.0
7f489c1ee000-7f489c1f1000 rw-p 00174000 07:00 146381                     /usr/local/lib/libopencv_calib3d.so.3.1.0
7f489c1f1000-7f489c371000 r-xp 00000000 07:00 146405                     /usr/local/lib/libopencv_videostab.so.3.1.0
7f489c371000-7f489c571000 ---p 00180000 07:00 146405                     /usr/local/lib/libopencv_videostab.so.3.1.0
7f489c571000-7f489c574000 rw-p 00180000 07:00 146405                     /usr/local/lib/libopencv_videostab.so.3.1.0
7f489c574000-7f489c5d5000 r-xp 00000000 07:00 146402                     /usr/local/lib/libopencv_superres.so.3.1.0
7f489c5d5000-7f489c7d5000 ---p 00061000 07:00 146402                     /usr/local/lib/libopencv_superres.so.3.1.0
7f489c7d5000-7f489c7d9000 rw-p 00061000 07:00 146402                     /usr/local/lib/libopencv_superres.so.3.1.0
7f489c7d9000-7f489c83f000 r-xp 00000000 07:00 146374                     /usr/local/lib/libopencv_objdetect.so.3.1.0
7f489c83f000-7f489ca3e000 ---p 00066000 07:00 146374                     /usr/local/lib/libopencv_objdetect.so.3.1.0
7f489ca3e000-7f489ca40000 rw-p 00065000 07:00 146374                     /usr/local/lib/libopencv_objdetect.so.3.1.0
7f489ca40000-7f489caeb000 r-xp 00000000 07:00 146399                     /usr/local/lib/libopencv_stitching.so.3.1.0
7f489caeb000-7f489ccea000 ---p 000ab000 07:00 146399                     /usr/local/lib/libopencv_stitching.so.3.1.0
7f489ccea000-7f489cced000 rw-p 000aa000 07:00 146399                     /usr/local/lib/libopencv_stitching.so.3.1.0
7f489cced000-7f489cd28000 r-xp 00000000 07:00 141827                     /usr/local/lib/libopencv_shape.so.3.1.0
7f489cd28000-7f489cf28000 ---p 0003b000 07:00 141827                     /usr/local/lib/libopencv_shape.so.3.1.0
7f489cf28000-7f489cf29000 rw-p 0003b000 07:00 141827                     /usr/local/lib/libopencv_shape.so.3.1.0
7f489cf29000-7f489cf57000 r-xp 00000000 07:00 2493870                    /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libmodule-lips2.so
7f489cf57000-7f489d157000 ---p 0002e000 07:00 2493870                    /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libmodule-lips2.so
7f489d157000-7f489d158000 r--p 0002e000 07:00 2493870                    /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libmodule-lips2.so
7f489d158000-7f489d15f000 rw-p 0002f000 07:00 2493870                    /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libmodule-lips2.so
7f489d15f000-7f489d191000 rw-p 00000000 00:00 0 
7f489d191000-7f489d1db000 r-xp 00000000 07:00 2493864                    /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libOniFile.so
7f489d1db000-7f489d3da000 ---p 0004a000 07:00 2493864                    /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libOniFile.so
7f489d3da000-7f489d3dc000 r--p 00049000 07:00 2493864                    /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libOniFile.so
7f489d3dc000-7f489d3dd000 rw-p 0004b000 07:00 2493864                    /home/myname/Downloads/LIPS-Linux-x64-OpenNI2.2/LIPS_Sample/Ni2SimpleViewer/OpenNI2/Drivers/libOniFile.so
7f489d3dd000-7f489d3fd000 rw-p 00000000 00:00 0 
7f489d3fd000-7f489ecb3000 r-xp 00000000 07:00 135624                     /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f489ecb3000-7f489eeb2000 ---p 018b6000 07:00 135624                     /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f489eeb2000-7f489eeb3000 r--p 018b5000 07:00 135624 Abort(Core dump)

**Comment by lips-hci** [comment]
Thanks for reporting this problem. SDK version 1.5.0.7 should fix it. Please have a try :)
You can get it from our website.
https://www.lips-hci.com/downloads/category

**Comment by naokiuchida** [comment]
Thank you for the update. I confirmed this problem is fixed in my environment.
